name: "transformer_word_lvl"
joeynmt_version: "2.2.0"


data:
    train: "data/train"
    dev:   "data/dev"
    test:  "data/test"
    dataset_type: "plain"
    src:
        lang: "nl"
        level: "word"
        lowercase: False
        voc_limit: 2000
    trg: 
        lang: "de"
        level: "word"
        lowercase: False
        voc_limit: 2000

testing:
    beam_size: 1
    beam_alpha: 1.0
    eval_metrics: ["bleu"]
    sacrebleu_cfg:
        tokenizer: "13a"

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    learning_rate: 0.0003
    batch_size: 2048
    batch_type: "token"
    scheduling: "plateau"
    patience: 8
    weight_decay: 0.0
    decrease_factor: 0.7
    early_stopping_metric: "bleu"
    epochs: 10
    validation_freq: 1000
    logging_freq: 100
    model_dir: "models/transformer_word_lvl"
    overwrite: True
    shuffle: True
    use_cuda: True
    print_valid_sents: [0, 1, 2, 3, 4]
    label_smoothing: 0.3
    keep_best_checkpoints: 3

model:
    initializer: "xavier_uniform"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier_uniform"
    embed_init_gain: 1.0
    tied_embeddings: False
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 4
        num_heads: 2
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0
        hidden_size: 256
        ff_size: 1024
        dropout: 0
    decoder:
        type: "transformer"
        num_layers: 1
        num_heads: 2
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0
        hidden_size: 256
        ff_size: 1024
        dropout: 0
